project:
  type: website
  output-dir: docs

website:
  title: "FacetGrid"
  navbar:
    left:
      - href: PSDV (1).ipynb
        text: Notebook
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



